### ISSUE TITLE
Research Machine Learning

### ISSUE THREAD

**Issue by MistySunMew** [MistySunMew/ElectronicsStorePOS#1]
Research Recommendation machine learning module included in Visual Studio and find out how to implement it.

**Comment by theZalmanian** [comment]
What is model builder and how does it work: [learn.microsoft.com/en-us/dotnet/machine-learning/](https://learn.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-model-builder#which-machine-learning-scenario-is-right-for-me )

**Comment by theZalmanian** [comment]
# You don't need machine learning expertise to use MB
All you need is some data, and a problem to solve. Model Builder generates the code to add the model to your .NET application.

## **Scenario**
*Recommendation* - The recommendation scenario predicts a **list of suggested items** for a particular user, **based on how similar their likes and dislikes are to other users**. 

You can use the recommendation scenario when you have a **set of users** and a **set of "products"**, such as items to purchase, movies, books, or TV shows, along with a **set of users' "ratings"** of those products.

## **Environment** 
*Local* - You can train your machine learning model locally on your machine or in the cloud on Azure, depending on the scenario.

## **Data** (See: [Loading training data into Model Builder](https://learn.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-model-builder))
Input types can be: 
-- File: .csv, .tsv, or .txt
-- Database: SQL Server

Required data for training:
-- Users (Customers)
-- Products
-- Product Rating

## **Training** 
Training is an **automatic process** by which Model Builder teaches your model how to answer questions for your scenario. Once trained, your model can make predictions with input data that it has not seen before.

Time required is **dependent on the size of dataset**. (See: [How long should I train for?](https://learn.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-model-builder#how-long-should-i-train-for) for detailed answer.)

## **Evaluate**
Evaluation is the process of measuring how good your model is. Model Builder uses the trained model to make predictions with new test data, and then measures how good the predictions are. See: [How do I understand my model performance?](https://learn.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-model-builder#how-do-i-understand-my-model-performance) for specifics

If evaluation is not optimal see: [Improving the model](https://learn.microsoft.com/en-us/dotnet/machine-learning/automate-training-with-model-builder#improve)

### Examples of recommendation at work using movie data-set:
![image](https://user-images.githubusercontent.com/103011701/213617588-13eda8c0-fe23-459d-82c0-0a92ca18b2d2.png)

![image](https://user-images.githubusercontent.com/103011701/213617930-3da3dd5b-129b-4f7b-ad0b-c6b412b1d8bb.png)

## Consume
After the evaluation phase, Model Builder outputs a model file, and code that you can use to add the model to your application. ML.NET models are saved as a zip file. The code to load and use your model is added as a new project in your solution. Model Builder also adds a sample console app that you can run to see your model in action.

In addition, Model Builder gives you the option to create projects that consume your model. Currently, Model Builder will create the following projects:

Console app: Creates a .NET Core console applications to make predictions from your model.
Web API: Creates an ASP.NET Core Web API that lets you consume your model over the internet.
