### ISSUE TITLE
Removing from cart does not save

### ISSUE THREAD

**Issue by theZalmanian** [MistySunMew/ElectronicsStorePOS#48]
You can remove a Product from the cart on the cart form- but this does not transfer over to the home form. 
Meaning you can remove the product, but next time you open the cart form it'll come back

**Comment by MistySunMew** [comment]
We should be able to solve this by sending the cart collection back to the home form, this could also be useful if we want to add a empty cart button that would send back an empty collection thus clearing the cart on the home form.
