### ISSUE TITLE
Polish up the README

### ISSUE THREAD

**Issue by theZalmanian** [MistySunMew/ElectronicsStorePOS#76]
Make necessary updates to the project README

**Comment by MistySunMew** [comment]
badge ideas
- https://img.shields.io/github/milestones/closed/MistySunMew/ElectronicsStorePOS
- https://img.shields.io/github/stars/MistySunMew/ElectronicsStorePOS?style=plastic
- https://img.shields.io/github/languages/top/MistySunMew/ElectronicsStorePOS
- https://img.shields.io/github/repo-size/MistySunMew/ElectronicsStorePOS
- https://img.shields.io/github/downloads/MistySunMew/ElectronicsStorePOS/total
- https://img.shields.io/github/manifest-json/v/MistySunMew/ElectronicsStorePOS
